#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn pretty ||
(
    echo '❌ Unable to format your code!';
    false;
)
echo '✅ Code is Pretty now.';

# Check ESLint Standards
(yarn check-lint && yarn pre-commit-lint) ||
(
        echo '😤👋😤 Follow lint standards 😤👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)
echo '✅ No Linting issue found.';

# Check tsconfig standards
yarn check-types ||
(
    echo '🤡❌🤡 Failed Type check. 🤡❌🤡
            Types check failed! Make the changes required above.'
    false;
)
echo '✅ No Typescript types issue found.';

yarn build ||
(
    echo '❌ Build failed ❌
            Types check failed! Make the changes required above.'
    false;
)
echo '✅ Build successfully.';
echo '✅💯👍 Success... Committing code. 👍💯✅'

